### ISSUE TITLE
Cleanup barrel files

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/graph-engine#458]
We are currently using a lot of barrel files which is impacting our final bundle size with treeshaking

We should both change these as well as use something like https://github.com/art0rz/eslint-plugin-no-barrel-files to catch this practice in the future

- One entrypoint per node (use * notation in pkg entrypoints)
- No index.js files importing index.js files
- CHeck if the eslint plugin can be set with boundaries (max re-exports)

**Comment by jorenbroekema** [comment]
Doesn't seem like that eslint plugin allows any re-exports whatsoever so maybe consider not using that one, since it's too restrictive.

Barrel files are mostly bad if:
- lots of re-exports
- multiple re-exports that have side effects

Barrel files grouping 3-5 side-effect-free small utils and re-exporting is totally fine. So if there is a plugin that understands that nuance, use it, if not, then don't use it I would say

**Comment by SorsOps** [comment]
Fixed in https://github.com/tokens-studio/studio-app/pull/1668

The worst part of these barrel files were that we had cyclical dependencies we did have a noticeable memory footprint with the typescript server. I did not add an eslint config, mainly because I agree that they aren't even and I don't want to make linting any more complicated then it is
